# Generated by Django 4.0.4 on 2022-04-17 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred', models.CharField(max_length=120)),
                ('pred_idx', models.CharField(max_length=120)),
                ('probs', models.CharField(max_length=120)),
                ('picture', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
